[package]
name = "ashlang"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.9", features = ["derive"] }
lazy_static = "1.5.0"
pest = "2.7.11"
pest_derive = "2.7.11"
triton-vm = "=0.41.0"
