WHITESPACE = _{ " " }
program = _{ SOI ~ "\n"* ~ (stmt ~ "\n"+) * ~ stmt? ~ EOI }

stmt = { vardef ~ "=" ~ expr ~ ";" }

char = _{ ASCII_ALPHANUMERIC | "_" }

varname = @{ char+ }
literal_dec = @{ ASCII_DIGIT+ }

atom = { literal_dec | varname }

let_r = { "let " }

vardef = { let_r? ~ varname }

op = _{ add | sub | mul | inv }
    add = { "+" }
    sub = { "-" }
    mul = { "*" }
    inv = { "/" }

expr = { atom ~ (op ~ expr)* }